ores:
  yellow_iron_ore:
    chance: 0.15
  bauxite:
    chance: 0.10
  blue_corundum:
    chance: 0.0001
  red_corundum:
    chance: 0.0001
  sphalerite:
    chance: 0.10
  stacked_zinc_ore:
    chance: 0.20
  smithsonite:
    chance: 0.10
  magnesium_zinc_ore:
    chance: 0.01
  red_zincite:
    chance: 0.10
  galena:
    chance: 0.08
  cerussite:
    chance: 0.04
  anglesite:
    chance: 0.02
  crocoite:
    chance: 0.03
  boulangerite:
    chance: 0.02
  jamesonite:
    chance: 0.10
  vanadinite:
    chance: 0.05
  wulfenite:
    chance: 0.05

geo_miner:
  bischofite:
    min: 1
    max: 3
  brine:
    min: 1
    max: 3
  carnallite:
    min: 1
    max: 3
  pyromorphite:
    min: 1
    max: 5
  mimetite:
    min: 1
    max: 5
  bournonite:
    min: 1
    max: 5
